### ISSUE TITLE
.env file

### ISSUE THREAD

**Issue by AdilHypeteq** [Moinak-Majumdar/PixelPerks#1]
where is .env file? can you please help me

**Comment by Moinak-Majumdar** [comment]
In single word No, You have to create a ```.env``` in your working directory, 

The env file contains my server SECRET, (it is optional if dont use any secret for your server)

SERVER_BASE=YOUR_SERVER_URL
SERVER_CATEGORY=YOUR_SERVER_URL/categorized (category endpoint)
SERVER_DETAILED=YOUR_SERVER_URL/fullImage (full image endpoint)

EMAIL="any email id"

Follow this repo to create your own express server.
https://github.com/Moinak-Majumdar/high-quality-image-server

Thank you for your interest ❤️
