### ISSUE TITLE
failed to connect server

### ISSUE THREAD

**Issue by anasssadik01** [Moinak-Majumdar/PixelPerks#4]
I have used the application, but the images do not appear to me when I choose Categories, but rather this message appears "failed to connect server"

**Comment by Moinak-Majumdar** [comment]
Hi @anasssadik01,

Thank you for bringing this issue to my attention. I understand that you are facing an error when choosing a specific predefined category in the app. It seems that the error might be related to the limited number of requests approx ```100``` per minute on the Pixabay free api.

To address this issue and ensure a smoother experience, I recommend you to bulid the app with your exclusive Pixabay api key.

1. Clone the Repository :
```
git clone https://github.com/Moinak-Majumdar/PixelPerks.git
```
2. Follow [Contribution Guidelines](https://github.com/Moinak-Majumdar/PixelPerks/blob/main/CONTRIBUTING.md) to setup yor ```.env``` file.  You can obtain an API key by registering on the [Pixabay](https://pixabay.com/api/docs/) website.
3. After setting up the .env file, build and run the PixelPerks app. This should resolve the issue, as you'll be using your own API key, ensuring a better experience with a higher request limit.

If you encounter any further issues or have additional questions, feel free to let me know.
