### ISSUE TITLE
.env file is missing!

### ISSUE THREAD

**Issue by haris-ali01** [Moinak-Majumdar/PixelPerks#5]
.env file is missing from the assests folder. App is not loading and display nothing.

**Comment by Moinak-Majumdar** [comment]
Hello, Please follow [README](https://github.com/Moinak-Majumdar/PixelPerks?tab=readme-ov-file#%EF%B8%8F-project-setup-%EF%B8%8F) or the [CONTRIBUTING.md](https://github.com/Moinak-Majumdar/PixelPerks/blob/main/CONTRIBUTING.md#1-getting-started-%EF%B8%8F) for the project setup guide.

Thanks for your kind attention.
